/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ExchangeRateService } from "../exchangeRate.service";
import { ExchangeRateCreateInput } from "./ExchangeRateCreateInput";
import { ExchangeRate } from "./ExchangeRate";
import { ExchangeRateFindManyArgs } from "./ExchangeRateFindManyArgs";
import { ExchangeRateWhereUniqueInput } from "./ExchangeRateWhereUniqueInput";
import { ExchangeRateUpdateInput } from "./ExchangeRateUpdateInput";

export class ExchangeRateControllerBase {
  constructor(protected readonly service: ExchangeRateService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ExchangeRate })
  async createExchangeRate(
    @common.Body() data: ExchangeRateCreateInput
  ): Promise<ExchangeRate> {
    return await this.service.createExchangeRate({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        rate: true,
        lastUpdated: true,
        targetCurrency: true,
        sourceCurrency: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ExchangeRate] })
  @ApiNestedQuery(ExchangeRateFindManyArgs)
  async exchangeRates(@common.Req() request: Request): Promise<ExchangeRate[]> {
    const args = plainToClass(ExchangeRateFindManyArgs, request.query);
    return this.service.exchangeRates({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        rate: true,
        lastUpdated: true,
        targetCurrency: true,
        sourceCurrency: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ExchangeRate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async exchangeRate(
    @common.Param() params: ExchangeRateWhereUniqueInput
  ): Promise<ExchangeRate | null> {
    const result = await this.service.exchangeRate({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        rate: true,
        lastUpdated: true,
        targetCurrency: true,
        sourceCurrency: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ExchangeRate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateExchangeRate(
    @common.Param() params: ExchangeRateWhereUniqueInput,
    @common.Body() data: ExchangeRateUpdateInput
  ): Promise<ExchangeRate | null> {
    try {
      return await this.service.updateExchangeRate({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          rate: true,
          lastUpdated: true,
          targetCurrency: true,
          sourceCurrency: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ExchangeRate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteExchangeRate(
    @common.Param() params: ExchangeRateWhereUniqueInput
  ): Promise<ExchangeRate | null> {
    try {
      return await this.service.deleteExchangeRate({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          rate: true,
          lastUpdated: true,
          targetCurrency: true,
          sourceCurrency: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
